//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GZOrderRelease
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string ApplicantId { get; set; }
        public string ProductType { get; set; }
        public string IssuingType { get; set; }
        public int OrderType { get; set; }
        public string OrderVersion { get; set; }
        public string Check_UserCode { get; set; }
        public string Review_UserCode { get; set; }
        public string IsNewMaterial { get; set; }
        public int IsProcessorQuality { get; set; }
        public string ProjectTitle { get; set; }
        public string SONO { get; set; }
        public string JDSNO { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int DrawingRecognition { get; set; }
        public int IsSecondBOM { get; set; }
        public string Office { get; set; }
        public string OfficeContacts { get; set; }
        public string Remark { get; set; }
        public System.DateTime BOMDate { get; set; }
        public int BOMFinish { get; set; }
        public string BOM_UserCode { get; set; }
        public string Issue_UserCode { get; set; }
        public string Implement1_UserCode { get; set; }
        public int ImplementFinish1 { get; set; }
        public string Implement2_UserCode { get; set; }
        public int ImplementFinish2 { get; set; }
        public string Implement3_UserCode { get; set; }
        public int ImplementFinish3 { get; set; }
        public string Implement4_UserCode { get; set; }
        public int ImplementFinish4 { get; set; }
    }
}
