//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GZOrderReview
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string ApplicantId { get; set; }
        public string ProductType { get; set; }
        public string IssuingType { get; set; }
        public int OrderType { get; set; }
        public int IsReview { get; set; }
        public string BOM_UserCode { get; set; }
        public string BOM_RealName { get; set; }
        public string NewPurchasing_UserCode { get; set; }
        public string NewPurchasing_RealName { get; set; }
        public string Assignment_UserCode { get; set; }
        public string Assignment_RealName { get; set; }
        public string ProjectTitle { get; set; }
        public string SONO { get; set; }
        public string JDSNO { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public int DrawingRecognition { get; set; }
        public int IsSecondBOM { get; set; }
        public string Office { get; set; }
        public string OfficeContacts { get; set; }
        public string OrderVersion { get; set; }
        public string Remark { get; set; }
        public string IsNewMaterial { get; set; }
        public System.DateTime DesignFinishDate { get; set; }
        public string Process_UserCode { get; set; }
        public string Process_RealName { get; set; }
        public System.DateTime ProcessFinishDate { get; set; }
        public string Quality_UserCode { get; set; }
        public string Quality_RealName { get; set; }
        public System.DateTime QualityFinishDate { get; set; }
        public string Purchasing_UserCode { get; set; }
        public string Purchasing_RealName { get; set; }
        public System.DateTime PurchasingFinishDate { get; set; }
        public string Electrical_UserCode { get; set; }
        public string Electrical_RealName { get; set; }
        public System.DateTime ElectricalFinishDate { get; set; }
        public string ETD_UserCode { get; set; }
        public string ETD_RealName { get; set; }
        public System.DateTime ETDFinishDate { get; set; }
        public string Director_UserCode { get; set; }
        public string Director_RealName { get; set; }
        public System.DateTime DirectorFinishDate { get; set; }
    }
}
