//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GZOrderReleaseAttachment
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string StepLabel { get; set; }
        public string EdocFileId { get; set; }
        public string EdocFolderId { get; set; }
        public string FileName { get; set; }
        public string FileExtName { get; set; }
        public string FileType { get; set; }
        public string FileNum { get; set; }
        public string FileDescribe { get; set; }
        public string SAP { get; set; }
        public string Version { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string Property { get; set; }
        public string IssuingDept { get; set; }
        public string Notes { get; set; }
        public string ExtendA { get; set; }
    }
}
