//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GZOrderReviewProduct
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string Item { get; set; }
        public string Material { get; set; }
        public string MaterialNum { get; set; }
        public string Requirement { get; set; }
        public string Remark { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime CrewFinishDate { get; set; }
    }
}
