//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GZOrderProcessConfig
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProductType { get; set; }
        public string Design_UserCode { get; set; }
        public string MPD_UserCode { get; set; }
        public string Check_UserCode { get; set; }
        public string Review_UserCode { get; set; }
        public string PUR_UserCode { get; set; }
        public string Issue_UserCode { get; set; }
        public string BOM_UserCode { get; set; }
        public string Implement_UserCode { get; set; }
        public string Implement1_UserCode { get; set; }
        public string Implement2_UserCode { get; set; }
        public string Implement3_UserCode { get; set; }
        public string Implement4_UserCode { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Process_UserCode { get; set; }
        public string Quality_UserCode { get; set; }
        public string Purchasing_UserCode { get; set; }
        public string Electrical_UserCode { get; set; }
        public string ETD_UserCode { get; set; }
        public string Director_UserCode { get; set; }
        public string PMC_UserCode { get; set; }
    }
}
