//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MailProcessConfig
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ProcessName { get; set; }
        public string StepLabel { get; set; }
        public int IsMailOpinion { get; set; }
        public int MailSendCycle { get; set; }
        public string Notes { get; set; }
    }
}
