//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Process
    {
        public string ProcessId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessName { get; set; }
        public int Incident { get; set; }
        public string Summary { get; set; }
        public string ProcessParentId { get; set; }
        public int ProcessStatus { get; set; }
        public Nullable<System.DateTime> SaveTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> AbortTime { get; set; }
        public Nullable<System.DateTime> IncidentTime { get; set; }
        public string Notes { get; set; }
    }
}
