//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQPrice
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string PN { get; set; }
        public string SQUnDescr { get; set; }
        public string SQSDescr { get; set; }
        public string SQLevel1 { get; set; }
        public string SQLevel2 { get; set; }
        public string SQLevel3 { get; set; }
        public string SQLevel4 { get; set; }
        public Nullable<decimal> SepMaterial { get; set; }
        public Nullable<decimal> StdMaterial { get; set; }
        public Nullable<decimal> LOADD { get; set; }
        public Nullable<decimal> EngFee { get; set; }
        public Nullable<decimal> typea { get; set; }
        public Nullable<decimal> typeb { get; set; }
        public Nullable<decimal> totleMLO { get; set; }
        public string TotalFiceBT { get; set; }
        public string QTY { get; set; }
        public string FiceTp { get; set; }
        public string TotalFiceAT { get; set; }
    }
}
