//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SQInfo
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string ProjectName { get; set; }
        public string SQNo { get; set; }
        public string SQFrom { get; set; }
        public string SaleOffice { get; set; }
        public string SQUnFrom { get; set; }
        public System.DateTime SQDate { get; set; }
        public string ChillerType { get; set; }
        public string UnitModel { get; set; }
        public string Quantity { get; set; }
        public string SQFor { get; set; }
        public string AppType { get; set; }
        public string EnquiryFrom { get; set; }
        public string QuoteBy { get; set; }
        public int Undesigntime { get; set; }
        public int Purchastingtime { get; set; }
        public string LeadtimeInfo { get; set; }
        public string Globalcode { get; set; }
        public string Versions { get; set; }
    }
}
