//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TaskApproval
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public string ProcessId { get; set; }
        public string SignKey { get; set; }
        public string TaskId { get; set; }
        public string StepLabel { get; set; }
        public int Opinion { get; set; }
        public string Comments { get; set; }
        public int ApprovalStatus { get; set; }
        public int ResultSignUserCount { get; set; }
        public int ResultSignOpinion { get; set; }
        public string IP { get; set; }
        public byte[] SignedPhotograph { get; set; }
        public int IsQueueOperation { get; set; }
        public Nullable<System.DateTime> SaveTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> QStartTime { get; set; }
        public Nullable<System.DateTime> QEndTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> FailedTime { get; set; }
        public int ProcessIsEnd { get; set; }
        public int IsCurrentBatch { get; set; }
        public string Notes { get; set; }
    }
}
