//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TimeJYCho
    {
        public int Id { get; set; }
        public string TypeA { get; set; }
        public string TypeB { get; set; }
        public string TypeC { get; set; }
    }
}
