//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data.EntityModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Travel
    {
        public string Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUserCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string ModifyUserCode { get; set; }
        public int DelStatus { get; set; }
        public string ProcessId { get; set; }
        public string ApplicantId { get; set; }
        public string ApplicantDeptId { get; set; }
        public string JobTitle { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> TravelStartDate { get; set; }
        public Nullable<System.DateTime> TravelEndDate { get; set; }
        public decimal Cost { get; set; }
        public string Test1 { get; set; }
        public string Test2 { get; set; }
        public string IsActiveSubProcess { get; set; }
        public string Currency { get; set; }
        public string TravelRemark { get; set; }
    }
}
